---
title: "polandshort"
output: html_document
date: "2025-03-13"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(careless)
library(ggplot2)
library(car)
library(psych)
library(dplyr)
library(gtsummary)
library(lavaan)
library(tidySEM)
library(haven)
library(semTools)
library(corrplot)
library(lavaan)
```

```{r}

#install.packages("fastDummies")

# Load the library
library(fastDummies)


# Create dummy variable
onlymanipulation <- fastDummies::dummy_cols(onlymanipulation, 
                               select_columns = "gr")
mand <- dummy_cols(mand, select_columns = "gr")



forsem <- onlymanipulation

which(is.na(forsem$gr))

forsem <- forsem[-c(123:125, 187, 188, 262,263), ]


```






Security - aggreement
```{r}
med.model <- '
  stateneedsecurity =~ security_freedom_1+security_freedom_2+security_freedom_3
  Mainstream=~nar5_end  +nar6_end  +nar7_end  +nar8_end  
  Micronarratives=~nar1_end+nar2_end+nar3_end+ nar4_end 
  traitneedsecurity=~ security_1+security_2+security_3

  Micronarratives ~b1*stateneedsecurity+traitneedsecurity
  Mainstream ~b2*stateneedsecurity+traitneedsecurity


  stateneedsecurity ~ a1*gr_1
  Micronarratives ~ gr_1
  Mainstream ~gr_1
  
ind1 := a1*b1
ind2 := a1*b2

'

med.fit <- sem(med.model, data = forsem, estimator = "ML", missing = "FIML", se = "bootstrap",bootstrap = 500L, parallel ="snow")
summary(med.fit, fit.measures=T, standardized = T, rsquare=TRUE)
estimates_med.fit <- parameterEstimates(med.fit, standardized=TRUE, boot.ci.type="perc", level=0.95,zstat = FALSE, pvalue = FALSE, output = "data.frame")

View(estimates_med.fit)
estimates_med.fit[61:62, ]
```

visualisation

```{r} 


library(semptools)
library(semPlot)

pm_no_covs <- semptools::drop_nodes(
  semPlotModel(med.fit),
  c("security_freedom_1", "security_freedom_2", "security_freedom_3", "nar5_end",
    "nar6_end", "nar7_end", "nar8_end", "nar1_end", "nar2_end", "nar3_end",
    "nar4_end", "security_1", "security_2", "security_3"))

pfad_layout<- get_layout("traitneedsecurity","", "", "","Micronarratives",
                         "","", "","","",
                         "stateneedsecurity","","","","",
                         "","","","","Mainstream",
                         "gr_1","","","","",
                         "security_freedom_1", "security_freedom_2", "security_freedom_3", "nar5_end", "",
                        "nar6_end", "nar7_end", "nar8_end", "nar1_end", "nar2_end", 
                        "nar3_end", "nar4_end", "security_1", "security_2", "security_3",
                         rows = 8)


pm <- semPaths(pm_no_covs, what= "std", layout = pfad_layout, residuals = FALSE,
               nCharNodes = 0, fade= FALSE, sizeLat = 9, sizeMan = 9, label.cex = 1.5, edge.label.cex =1,
               intercepts = F, equalizeManifests=F, exoCov = F)


#add statistical significance asteriscs
library(semptools)
my_label_list <- list(list(node = "traitneedsecurity", to = "(T) Need for \nsecurity"),
                      list(node = "stateneedsecurity", to = "(S) Need for \nsecurity"),
                      list(node = "Micronarratives", to = "Anti-mainstream \nnarratives"),
                      list(node = "Mainstream", to = "Mainstream \nnarratives"),
                      list(node = "gr_1", to = "Group \n(vol=0, mand=1"))

p_pa2 <- mark_sig(pm, med.fit)
p_pa2 <- change_node_label(p_pa2, my_label_list)

plot(p_pa2)
```


Interest

```{r}
medint.model <- '
  needsecurity =~ security_freedom_1+security_freedom_2+security_freedom_3
  Mainstream=~Nar_5correct  +nar_6correct  +nar_7correct  +nar_8correct  
  Micronarratives=~nar_1+nar_2+nar_3+ nar_4 
  traitneedsecurity=~ security_1+security_2+security_3

  Micronarratives ~b1*needsecurity+traitneedsecurity
  Mainstream ~b2*needsecurity+traitneedsecurity


  needsecurity ~ a1*gr_1
  Micronarratives ~ gr_1
  Mainstream ~gr_1
  
ind1 := a1*b1
ind2 := a1*b2

'

medint.fit <- sem(medint.model, data = forsem, estimator = "ML", missing = "FIML", se = "bootstrap",bootstrap = 5000L, parallel ="snow")
summary(medint.fit, fit.measures=T, standardized = T, rsquare=TRUE)
estimates_medint.fit <- parameterEstimates(medint.fit, standardized=TRUE, boot.ci.type="perc", level=0.95,zstat = FALSE, pvalue = FALSE, output = "data.frame")

View(estimates_medint.fit)
estimates_medint.fit[61:62, ]
```


```{r}
pfad_layout<- get_layout("","traitsecurity", "", "","Micronarratives",
                         "","", "","","",
                         "gr_2","","","","",
                         "","","","","Mainstream",
                         "","security","","","",
                         rows = 5)

tidySEM::graph_sem(model = m.fit_final, layout = pfad_layout) 


summary(aov(institution_trust_5 ~ gr, data= onlymanipulation))

```

Trust - agreement
```{r}
talt.model <- '
  stateneedsecurity =~ security_freedom_1+security_freedom_2+security_freedom_3
  Mainstream=~nar5_end  +nar6_end  +nar7_end  +nar8_end  
  Micronarratives=~nar1_end+nar2_end+nar3_end+ nar4_end 
  traitneedsecurity=~ security_1+security_2+security_3

  institution_trust_5 ~ b1*Micronarratives
  institution_trust_5 ~b2*Mainstream
  Micronarratives ~a1*stateneedsecurity+traitneedsecurity
  Mainstream ~ a2*stateneedsecurity+traitneedsecurity
  Micronarratives ~ gr_1
  Mainstream ~gr_1

  stateneedsecurity ~ gr_1
  institution_trust_5~ gr_1 
  institution_trust_5 ~ stateneedsecurity
      
ind1 := a1*b1
ind2 := a2*b2

'


talt.fit <- sem(talt.model, data = forsem, estimator = "ML", missing = "FIML", se = "bootstrap",bootstrap = 500L, parallel ="snow")
summary(talt.fit, fit.measures=T, standardized = T, rsquare=TRUE)
estimates_talt.fit <- parameterEstimates(talt.fit, standardized=TRUE, boot.ci.type="perc", level=0.95,zstat = FALSE, pvalue = FALSE, output = "data.frame")

View(estimates_talt.fit)

estimates_talt.fit[64:65, ]
```
```{r}

tm_no_covs <- semptools::drop_nodes(
  semPlotModel(talt.fit),
  c("security_freedom_1", "security_freedom_2", "security_freedom_3", "nar5_end",
    "nar6_end", "nar7_end", "nar8_end", "nar1_end", "nar2_end", "nar3_end",
    "nar4_end", "security_1", "security_2", "security_3"))

pfad_layout<- get_layout("","", "Micronarratives", "","",
                         "traitneedsecurity","", "","","institution_trust_5",
                         "stateneedsecurity","","","","",
                         "gr_1","","Mainstream","","",
                         "security_freedom_1", "security_freedom_2", "security_freedom_3", "nar5_end", "",
                        "nar6_end", "nar7_end", "nar8_end", "nar1_end", "nar2_end", 
                        "nar3_end", "nar4_end", "security_1", "security_2", "security_3",
                         rows = 7)


tm <- semPaths(tm_no_covs, what= "std", layout = pfad_layout, residuals = FALSE,
               nCharNodes = 0, fade= FALSE, sizeLat = 9, sizeMan = 9, label.cex = 1.6, edge.label.cex =1,
               intercepts = F, equalizeManifests=F, exoCov = F)
my_label_list <- list(list(node = "traitneedsecurity", to = "(T) Need for \nsecurity"),
                      list(node = "stateneedsecurity", to = "(S) Need for \nsecurity"),
                      list(node = "institution_trust_5", to = "Trust in \nthe government"),
                      list(node = "Micronarratives", to = "Anti-mainstream \nnarratives"),
                      list(node = "Mainstream", to = "Mainstream \nnarratives"),
                      list(node = "gr_1", to = "Group \n(vol=0, mand=1"))
          

#add statistical significance asteriscs
library(semptools)

tp_pa2 <- mark_sig(tm, talt.fit)
tp_pa2 <- change_node_label(tp_pa2, my_label_list)
plot(tp_pa2)

```



security, interest, trust

```{r}
int_talt.model <- '
  needsecurity =~ security_freedom_1+security_freedom_2+security_freedom_3
  intMainstream=~Nar_5correct  +nar_6correct  +nar_7correct  +nar_8correct  
  intMicronarratives=~nar_1+nar_2+nar_3+ nar_4 
  traitneedsecurity=~ security_1+security_2+security_3

  institution_trust_5 ~ b1*intMicronarratives
  institution_trust_5 ~b2*intMainstream
  intMicronarratives ~a1*needsecurity+traitneedsecurity
  intMainstream ~ a2*needsecurity+traitneedsecurity
  intMicronarratives ~ gr_1
  intMainstream ~gr_1

  needsecurity ~ gr_1
  institution_trust_5~ gr_1 
  institution_trust_5 ~ needsecurity
      
ind1 := a1*b1
ind2 := a2*b2

'


int_talt.fit <- sem(int_talt.model, data = forsem, estimator = "ML", missing = "FIML", se = "bootstrap",bootstrap = 500L, parallel ="snow")
summary(int_talt.fit, fit.measures=T, standardized = T, rsquare=TRUE)
estimates_int_talt.fit <- parameterEstimates(int_talt.fit, standardized=TRUE, boot.ci.type="perc", level=0.95,zstat = FALSE, pvalue = FALSE, output = "data.frame")

View(estimates_int_talt.fit)

estimates_int_talt.fit[64:65, ]
```

```{r}
pfad_layout<- get_layout("","traitneedsecurity", "Micronarratives", "","",
                         "","", "","","",
                         "gr_2","","","","institution_trust_5",
                         "","","","Mainstream","",
                         "needsecurity","","","","",
                         rows = 5)

tidySEM::graph_sem(model = talt.fit, layout = pfad_layout) 


```


Active media use

```{r}
amed.model <- '
  needsecurity =~ security_freedom_1+security_freedom_2+security_freedom_3
  Mainstream=~nar5_end  +nar6_end  +nar7_end  +nar8_end  
  Micronarratives=~nar1_end+nar2_end+nar3_end+ nar4_end 
  traitneedsecurity=~ security_1+security_2+security_3

  
  Micronarratives ~needsecurity+traitneedsecurity+institution_trust_5+b1*active_soc_media
  Mainstream ~needsecurity+traitneedsecurity+institution_trust_5+b2*active_soc_media
  active_soc_media ~ a1*needsecurity

  needsecurity ~ gr_2
  institution_trust_5~ gr_2 
  institution_trust_5 ~ needsecurity
      
ind1 := a1*b1
ind2 := a1*b2

'


amed.fit <- sem(amed.model, data = forsem, estimator = "ML", missing = "FIML",
                se = "bootstrap",bootstrap = 500L, parallel ="snow")
summary(amed.fit, fit.measures=T, standardized = T, rsquare=TRUE)
estimates_amed.fit <- parameterEstimates(amed.fit, standardized=TRUE, boot.ci.type="perc", level=0.95,
                                         zstat = FALSE, pvalue = FALSE, output = "data.frame")

View(estimates_amed.fit)




estimates_amed.fit[70:71, ]
```


```{r}
pfad_layout<- get_layout("","traitneedsecurity", "", "","Micronarratives",
                         "","", "","","",
                         "gr_2","institution_trust_5","","active_soc_media","",
                         "","","","","",
                         "needsecurity","","","","Mainstream",
                         rows = 5)

tidySEM::graph_sem(model = a.fit, layout = pfad_layout) 


```



```{r}

dmcforsem <- forsem

#double mean centering
library(semTools)
dmcforsem <- indProd(dmcforsem, var1= c("security_freedom_1", "security_freedom_2", "security_freedom_3"),
                     var2=c("active_soc_media"),
                     match = FALSE , meanC = TRUE ,
                     residualC = FALSE , doubleMC = TRUE) 
amed.model <- '
stateneedsecurity =~ security_freedom_1+security_freedom_2+security_freedom_3
  Mainstream=~nar5_end  +nar6_end  +nar7_end  +nar8_end  
  Micronarratives=~nar1_end+nar2_end+nar3_end+ nar4_end 
  traitneedsecurity=~ security_1+security_2+security_3
  interaction=~ security_freedom_1.active_soc_media +security_freedom_2.active_soc_media + security_freedom_3.active_soc_media 
  
  
  Micronarratives ~stateneedsecurity+traitneedsecurity+active_soc_media+interaction
  Mainstream ~stateneedsecurity+traitneedsecurity+active_soc_media+interaction
  active_soc_media ~ stateneedsecurity

  institution_trust_5 ~ Micronarratives
  institution_trust_5 ~Mainstream
  Micronarratives ~ gr_1
  Mainstream ~gr_1

  stateneedsecurity ~ gr_1
  institution_trust_5~ gr_1 
  institution_trust_5 ~ stateneedsecurity
'

amed.fit <- sem(amed.model, data = dmcforsem, estimator = "MLM")
summary(amed.fit, fit.measures=T, standardized = T, rsquare=TRUE)
estimates_amed.fit <- parameterEstimates(amed.fit, standardized=TRUE, boot.ci.type="perc", level=0.95,
                                         zstat = FALSE, pvalue = FALSE, output = "data.frame")

View(estimates_amed.fit)

estimates_amed.fit[71:72, ]

```



```{r}

am_no_covs <- semptools::drop_nodes(
  semPlotModel(amed.fit),
  c("security_freedom_1", "security_freedom_2", "security_freedom_3", "nar5_end",
    "nar6_end", "nar7_end", "nar8_end", "nar1_end", "nar2_end", "nar3_end",
    "nar4_end", "security_1", "security_2", "security_3", "security_freedom_1.active_soc_media", "security_freedom_2.active_soc_media",  "security_freedom_3.active_soc_media" ))

a_pfad_layout<- get_layout("","","traitneedsecurity", "", "Micronarratives","",
                         "","active_soc_media","", "","","interaction",
                         "","","","","","",
                         "","stateneedsecurity","","","","institution_trust_5",
                         "","gr_1","","","","",
                         "","","","","Mainstream","",
                         "","","","","","",
                         "","ssec1", "ssec2", "ssec3", "narrative_2", "narrative_4", 
                         "","narrative_6","narrative_8","tsec1","tsec2","tsec3", 
                         "","narrative_1","narrative_3", "narrative_5", "narrative_7", "",
                         "","ssec1.med_act","ssec2.med_act","ssec3.med_act", "","",
             "security_freedom_1.active_soc_media", "security_freedom_2.active_soc_media", "security_freedom_3.active_soc_media", "","", "",
                         rows = 12)


am <- semPaths(am_no_covs, what= "std", layout = a_pfad_layout, residuals = FALSE,
               nCharNodes = 0, fade= FALSE, sizeLat = 8, sizeMan = 6, label.cex = 2, edge.label.cex =1,
               intercepts = F, equalizeManifests=F, exoCov = F)


#add statistical significance asteriscs
library(semptools)
my_label_list <- list(list(node = "traitneedsecurity", to = "(T) Need for \nsecurity"),
                      list(node = "stateneedsecurity", to = "(S) Need for \nsecurity"),
                      list(node = "institution_trust_5", to = "Trust in \nthe government"),
                      list(node = "active_soc_media", to = "Active \nmedia use"),
                      list(node = "interaction", to = "Interaction \nterm"),
                      list(node = "Micronarratives", to = "Anti-mainstream \nnarratives"),
                      list(node = "Mainstream", to = "Mainstream \nnarratives"),
                      list(node = "gr_1", to = "Group \n(vol=0, mand=1)"))


ap_pa2 <- mark_sig(am, amed.fit)
ap_pa2 <- change_node_label(ap_pa2, my_label_list)

plot(ap_pa2)
```


getwd()





freedom -- agreement

```{r}

frmed.model <- '
  needfreedom =~ security_freedom_4+security_freedom_5+security_freedom_6
  Mainstream=~nar5_end  +nar6_end  +nar7_end  +nar8_end  
  Micronarratives=~nar1_end+nar2_end+nar3_end+ nar4_end 
  traitneedfreedom=~ security_4+security_5+security_6

  Micronarratives ~b1*needsecurity+traitneedsecurity
  Mainstream ~b2*needsecurity+traitneedsecurity


  needsecurity ~ a1*gr_1
  Micronarratives ~ gr_1
  Mainstream ~gr_1
  
ind1 := a1*b1
ind2 := a1*b2

'

frmed.fit <- sem(frmed.model, data = forsem, estimator = "ML", missing = "FIML", se = "bootstrap",bootstrap = 5000L, parallel ="snow")
summary(frmed.fit, fit.measures=T, standardized = T, rsquare=TRUE)
estimates_frmed.fit <- parameterEstimates(frmed.fit, standardized=TRUE, boot.ci.type="perc", level=0.95,zstat = FALSE, pvalue = FALSE, output = "data.frame")

View(estimates_frmed.fit)
estimates_frmed.fit[61:62, ]
```





```{r}
#both
ldl.model <- '
  needsecurity =~ security_freedom_1+security_freedom_2+security_freedom_3
  likeMainstream=~q5_sm_2 +q6_sm_2+q7_sm_2 
 likeMicronarratives=~q1_sm_2 +q2_sm_2+q3_sm_2
  dislikeMainstream=~q5_sm_6 +q6_sm_6+q7_sm_6
  dislikeMicronarratives=~q1_sm_6 +q2_sm_6+q3_sm_6
  traitneedsecurity=~ security_1+security_2+security_3

  
  likeMicronarratives ~needsecurity+traitneedsecurity+gr_2
  likeMainstream ~needsecurity+traitneedsecurity+gr_2

  dislikeMicronarratives ~needsecurity+traitneedsecurity+gr_2
  dislikeMainstream ~needsecurity+traitneedsecurity+gr_2

institution_trust_5 ~ likeMicronarratives
institution_trust_5 ~likeMainstream
likeMicronarratives ~needsecurity+traitneedsecurity
likeMainstream ~ needsecurity+traitneedsecurity

institution_trust_5 ~ dislikeMicronarratives
institution_trust_5 ~dislikeMainstream
dislikeMicronarratives ~needsecurity+traitneedsecurity
dislikeMainstream ~ needsecurity+traitneedsecurity

needsecurity ~ gr_2
institution_trust_5~ gr_2 
institution_trust_5 ~ needsecurity
      dislikeMicronarratives~~likeMicronarratives
dislikeMainstream~~likeMainstream
      dislikeMicronarratives~~likeMainstream
dislikeMainstream~~likeMicronarratives

'

ldl.fit <- sem(ldl.model, data = forsem, estimator = "ML")
summary(ldl.fit, fit.measures=T, standardized = T, rsquare=TRUE)

```








